package com.cagrikilic.hepsiburadaseniorproject.network.model


import com.squareup.moshi.Json

data class Software(
    @Json(name = "advisories")
    var advisories: List<String>?,
    @Json(name = "appletvScreenshotUrls")
    var appletvScreenshotUrls: List<Any>?,
    @Json(name = "artistId")
    var artistId: Int?,
    @Json(name = "artistName")
    var artistName: String?,
    @Json(name = "artistViewUrl")
    var artistViewUrl: String?,
    @Json(name = "artworkUrl100")
    var artworkUrl100: String?,
    @Json(name = "artworkUrl512")
    var artworkUrl512: String?,
    @Json(name = "artworkUrl60")
    var artworkUrl60: String?,
    @Json(name = "averageUserRating")
    var averageUserRating: Double?,
    @Json(name = "averageUserRatingForCurrentVersion")
    var averageUserRatingForCurrentVersion: Double?,
    @Json(name = "bundleId")
    var bundleId: String?,
    @Json(name = "contentAdvisoryRating")
    var contentAdvisoryRating: String?,
    @Json(name = "currency")
    var currency: String?,
    @Json(name = "currentVersionReleaseDate")
    var currentVersionReleaseDate: String?,
    @Json(name = "description")
    var description: String?,
    @Json(name = "features")
    var features: List<String>?,
    @Json(name = "fileSizeBytes")
    var fileSizeBytes: String?,
    @Json(name = "formattedPrice")
    var formattedPrice: String?,
    @Json(name = "genreIds")
    var genreIds: List<String>?,
    @Json(name = "genres")
    var genres: List<String>?,
    @Json(name = "ipadScreenshotUrls")
    var ipadScreenshotUrls: List<String>?,
    @Json(name = "isGameCenterEnabled")
    var isGameCenterEnabled: Boolean?,
    @Json(name = "isVppDeviceBasedLicensingEnabled")
    var isVppDeviceBasedLicensingEnabled: Boolean?,
    @Json(name = "kind")
    var kind: String?,
    @Json(name = "languageCodesISO2A")
    var languageCodesISO2A: List<String>?,
    @Json(name = "minimumOsVersion")
    var minimumOsVersion: String?,
    @Json(name = "price")
    var price: Double?,
    @Json(name = "primaryGenreId")
    var primaryGenreId: Int?,
    @Json(name = "primaryGenreName")
    var primaryGenreName: String?,
    @Json(name = "releaseDate")
    var releaseDate: String?,
    @Json(name = "releaseNotes")
    var releaseNotes: String?,
    @Json(name = "screenshotUrls")
    var screenshotUrls: List<String>?,
    @Json(name = "sellerName")
    var sellerName: String?,
    @Json(name = "sellerUrl")
    var sellerUrl: String?,
    @Json(name = "supportedDevices")
    var supportedDevices: List<String>?,
    @Json(name = "trackCensoredName")
    var trackCensoredName: String?,
    @Json(name = "trackContentRating")
    var trackContentRating: String?,
    @Json(name = "trackId")
    var trackId: Int?,
    @Json(name = "trackName")
    var trackName: String?,
    @Json(name = "trackViewUrl")
    var trackViewUrl: String?,
    @Json(name = "userRatingCount")
    var userRatingCount: Int?,
    @Json(name = "userRatingCountForCurrentVersion")
    var userRatingCountForCurrentVersion: Int?,
    @Json(name = "version")
    var version: String?,
    @Json(name = "wrapperType")
    var wrapperType: String?
)